#!/usr/bin/env python3
from rhc_release_contracts import version_from_model
from pathlib import Path
import re, sys
root=Path(__file__).resolve().parents[1]
setup_path=root/'setup/setup-razer-inventory-v1.0.6.ps1'
setup=setup_path.read_text(encoding='utf-8')
health=(root/'health-engine-v1.4.6.ps1').read_text(encoding='utf-8')
sg=(root/'setupscan.go').read_text(encoding='utf-8')
engine=(root/'engine.go').read_text(encoding='utf-8')
ui=(root/'ui.go').read_text(encoding='utf-8')
model=(root/'model.go').read_text(encoding='utf-8')
main=(root/'main.go').read_text(encoding='utf-8')
hist=(root/'history_export.go').read_text(encoding='utf-8')
runtime=(root/'runtime.go').read_text(encoding='utf-8')
dm=(root/'device_monitor.go').read_text(encoding='utf-8')
portable=(root/'tools/package_portable.py').read_text(encoding='utf-8')
locale=(root/'locales/de-DE.json').read_text(encoding='utf-8')
errors=[]
def req(c,m):
    if not c: errors.append(m)
req(f'appVersion                   = "{version_from_model(root)}"' in model,'current application version missing')
req('engineVersion                = "1.4.6"' in model,'engine version 1.4.5 missing')
req(setup_path.is_file(),'Setup Scanner 1.0.6 source missing')
req(len(list((root/'setup').glob('setup-razer-inventory-*.ps1')))==1,'active embed setup dir must contain exactly one scanner source')
req(re.search(r"(?im)^\s*\$VendorId\s*=\s*'1532'\s*$", setup) is not None,'Razer VID scan root missing')
req("VID_1532&PID_[0-9A-F]{4}" in setup,'generic Razer VID/PID enumeration missing')
req('Win32_PnPEntity' in setup and 'Win32_PnPSignedDriver' in setup,'PnP/signed-driver inventory probes missing')
req('pnputil.exe" /enum-drivers' in setup,'read-only pnputil enumeration missing')
req('CurrentControlSet\\Enum' in setup,'historical alternate connection inventory missing')
req('logicalProductIds' in setup and 'isPowerOn' in setup,'logical product discovery missing')
req('schemaVersion = 2' in setup and re.search(r"(?im)^\s*\$ScanVersion\s*=\s*'1\.0\.6'\s*$", setup) is not None,'setup schema/version missing')
req('RazerDeviceInventory-v2.json' in main,'persistent schema-2 inventory path missing')
req('RazerConnectionHistory-v2.json' in main and 'connectionHistoryPath' in model,'persistent connection-history path missing')
req('inventorySchemaVersion = 2' in sg and 'setupScanVersion = "1.0.6"' in sg,'host setup schema/scanner versions missing')
req('DeviceConnectionCapabilities' in sg and 'DeviceConnectionTopology' in sg and 'ConnectionTypeConfidence' in sg,'host identity/role fields missing')
req('func (d DeviceInventory) valid() bool' in sg and 'validInventoryPID' in sg,'inventory validation missing')
req('setupContinueHealth' in model and 'HEALTH blocked setupReady=false' in engine,'health setup gate missing')
req('a.startSetupScan()' in engine,'automatic setup before health missing')
req(' -InventoryPath ' in engine and '$InventoryPath' in health,'health inventory contract missing')
req('$DeviceProducts' in health and '$DeviceConnections' in health and '$RequiredProducts' in health,'health device-profile consumption missing')
req("$DevicePids = @($RequiredProducts" in health,'health PIDs not derived from required products')
req("'Razer Geräte Live-PnP'" in health,'generic device gate name missing')
req('gate.devices.name' in model and 'gate.blackwidow.name' not in model,'UI still BlackWidow-specific')
req('nav.setup' in ui and 'drawSetupView' in ui,'Setup view missing')
req('items := []string{tr("nav.setup"), tr("nav.status"), tr("nav.logs"), tr("nav.info")}' in ui,'Setup not first sidebar view')
req('AppSession/Setup/' in hist and 'SetupScan-' in hist,'setup artifacts not exported')
req('connectionHistoryPath' in hist and 'RazerConnectionHistory-v2.json' in main,'connection history not exported')
req('//go:embed health-engine-v1.4.6.ps1 diagnostics repair setup assets' in runtime,'setup/health source not embedded')
req('setup/setup-razer-inventory-v1.0.6.ps1' in runtime,'setup runtime source version missing')
req('Runtime/setup' in portable and "'Setup'" in portable,'portable Setup/runtime structure missing')
req("Group-Object -Property { [string]$_['productKey'] }" in setup,'dictionary-safe product grouping missing')
req('Get-OptionalPropertyString' in setup and "'FriendlyName'" in setup,'StrictMode-safe registry optional-property access missing')
req('SetupScannerDebug-v1.0.6.json' in setup and 'SetupScannerDebug-v1.0.6.txt' in setup,'setup scanner debug artifacts missing')
req('copySetupDebugArtifact' in sg and 'SetupScannerDebug-' in sg,'setup debug persistence missing')
req('procSetTimer.Call(a.hwnd, 1, 125, 0)' in sg,'setup animation timer missing')
req('setupScanning := app.setupScanning' in ui and 'checking || setupScanning' in ui,'setup progress repaint timer missing')
req('func drawSetupScanOverlay' in ui and 'barW := tableW * 70 / 100' in ui and 'colors.green' in ui,'centered 70-percent Acid Green setup progress overlay missing')
req('darkenRect(hdc, table, 128)' in ui,'setup inventory fade overlay missing')
req('drawSetupConnectionSummary' in ui and 'liveFresh && ok && c.PresentAtScan' in ui and 'entryColor = colors.green' in ui and 'drawPart(role+" · ", entryColor)' in ui and 'drawPart(pid, entryColor)' in ui,'present typed connection Acid Green rendering missing')
req('setupPresentConnectionCount(inv)' in ui and '"present", setupPresentConnectionCount(inv)' in ui,'ready summary present-connection count missing')
req('drawSetupDeviceClassIcon' in ui and 'setupProductDeviceClass(inv, product)' in ui,'setup product device-class icons missing')
req('storedConnectionDeviceClass' in sg and 'drawSetupDeviceClassIcon(hdc, setupProductDeviceClass(a.inventory, product)' in ui,'guided calibration device-class icon missing')
req('Get-ConnectionDeviceClass' in setup and 'deviceClass = $deviceClass' in setup and 'deviceClass = $productDeviceClass' in setup,'generic device-class discovery missing')
req("MI_00" in setup and "Mouse|Keyboard" in setup,'primary HID class device-type evidence missing')
req('secondary := rect{406, actionTop, 686, actionBottom}' in ui and 'action.setup_calibrate' in ui,'guided calibration action card missing')
req('x >= 406 && x <= 686 && ready' in ui and 'openSetupCalibration' in ui,'guided calibration action handling missing')
req('SetupScannerDebug-' in hist,'setup scanner debug diagnostics not exported')
req(not any((root/'setup').glob('setup-razer-live-*.ps1')),'PowerShell live probe must not remain in active setup runtime')
req('native-setupapi-usb' in dm,'native SetupAPI live probe missing')
req('procSetupDiGetClassDevsW.Call' in dm and 'utf16("USB")' in dm,'native present USB enumeration missing')
req('devpkeyDeviceBusReportedDeviceDesc' in dm and 'IdentityVerified' in dm,'native bus-reported product verification missing')
req('RegisterDeviceNotificationW' in (root/'win32.go').read_text(encoding='utf-8'),'Windows device-change registration missing')
req('requestLivePresenceRefresh("startup"' in main,'startup live refresh missing')
req('SetupLiveProbe-v1.1.0.json' in hist,'native live probe diagnostic export missing')
req('setup.state.snapshot.detail' in ui,'stale inventory UI state missing')
req('storedConnectionDeviceClass' in sg and 'mouhid' in sg and 'kbdhid' in sg,'legacy device-class recovery missing')
# Generic identity architecture.
req('DEVPKEY_Device_BusReportedDeviceDesc' in setup,'bus-reported device identity missing')
req('Get-RootIdentity' in setup and 'Get-PnpDeviceProperty -InstanceId $InstanceId' in setup,'root identity probe missing')
req('Fast identity path: one Get-PnpDeviceProperty call for the physical USB' in setup,'root-only performance contract missing')
req('productIdentitySource' in setup and 'productIdentityConfidence' in setup,'identity provenance fields missing')
req('persistent-connection-history' in setup,'history identity fallback missing')
# Generic role architecture.
req('$HistoryPath' in setup and 'Read-ConnectionHistory' in setup and 'RazerConnectionHistory-v2.json' in setup,'persistent role learning missing')
req('connectionTypeConfidence' in setup and 'connectionFingerprint' in setup,'role confidence/fingerprint missing')
req('Get-ExplicitConnectionRole' in setup and 'explicit-device-role-text' in setup,'explicit role evidence missing')
req('topology-hid-collection-asymmetry' not in setup,'passive topology role inference must stay disabled')
req('topology-transition-confirmed' not in setup,'passive transition role promotion must stay disabled')
req('user-guided-wired-transition' in setup and 'user-guided-wireless-transition' in setup,'guided transition role learning missing')
req('user-guided-wired-reference' in setup and 'user-guided-wireless-reference' in setup,'guided reference role learning missing')
req('CalibrationMode' in setup and 'CalibrationProductKey' in setup and 'BaselinePath' in setup,'guided calibration scanner contract missing')
req('schemaVersion = 2' in setup and 'calibratedAt' in setup and 'calibrated = $calibrated' in setup,'connection history schema-2 calibration metadata missing')
req('hidCollectionCount' in setup and 'hidInterfaceCount' in setup and 'usbInterfaceCount' in setup,'lightweight topology metrics missing')
req('setupConnectionSummary' in sg and 'setupConnectionRoleLabel' in sg and 'ConnectionTypeConfidence' in sg and 'setup.connection.wireless_dongle' in sg and 'setup.connection.wired_usb' in sg,'role display missing')
req('verified-four-state-pnp-matrix-2026-09-10' not in sg,'host still depends on old PID evidence marker')
req('VerifiedConnectionTypes' not in setup,'hard-coded role map remains')
req("if ($Name -match '(?i)wireless|hyperspeed')" not in setup,'marketing-name connection heuristic must stay removed')
for token in ['driverStack','razerDriverInfNames','inboxDriverInfNames','requiresRzVirtual','requiresRzControl','requiresRazerBoundNodes','requiresDeviceFilters']:
    req(token in setup,'scanner capability field missing: '+token)
req("$physicalCmdNodes" in setup and "$physicalCimNodes" in setup,'physical presence separation missing')
req('"setup.connection.wireless_dongle"' in locale and '"setup.connection.wired_usb"' in locale,'role i18n missing')
req('Razer-Geräte und deren bekannte Verbindungswege werden inventarisiert.' in locale,'plain setup scan status text missing')
req('{present} aktuell verbunden' in locale,'ready summary active-connection wording missing')
# Capability-aware Health Gates 2-6.
req('razerDriverInfNames' in health and "Inventar Razer-INF" in health,'DriverStore not limited to Razer INF domain')
req('Windows-Inbox-HID-Treiber' in health,'Inbox driver non-failure evidence missing')
req('Get-ConnectionCapability' in health and 'Test-ConnectionUsesRazerStack' in health,'health capability helpers missing')
req("PID $devicePid Razer binding stack" in health and "'nicht anwendbar'" in health,'non-applicable binding path missing')
req("requiresDeviceFilters" in health and "'Device filters' 'INFO'" in health,'non-applicable filter path missing')
req("$_.Status -eq 'FAIL' -or $_.Status -eq 'UNKNOWN'" in health,'gate PASS logic must ignore INFO non-applicable checks')
# Active production code must not contain endpoint PID/model constants.
for token in ['00C0','00C1','02C9','02CC','BlackWidow','Viper V3 Pro','RzDev_02c9','RzDev_02cc','Logical product 716']:
    if token.lower() in health.lower(): errors.append('active health engine hardcodes device token: '+token)
    if token.lower() in setup.lower(): errors.append('active setup scanner hardcodes device token: '+token)
    if token.lower() in dm.lower(): errors.append('active native live probe hardcodes device token: '+token)
# Scanner may write its own app-owned inventory/history/debug files only; reject system mutation commands.
for token in ['Set-ItemProperty','New-ItemProperty','Remove-ItemProperty','Set-Service','Start-Service','Stop-Service','Restart-Service','New-Service','Remove-Service','Enable-PnpDevice','Disable-PnpDevice','devcon','pnputil.exe /add-driver','pnputil.exe /delete-driver','reg.exe add','reg.exe delete','sc.exe config','sc.exe start','sc.exe stop']:
    if token.lower() in setup.lower(): errors.append('setup mutation token: '+token)
# Health remains read-only.
for token in ['Set-ItemProperty','New-ItemProperty','Remove-ItemProperty','Set-Service','Start-Service','Stop-Service','Restart-Service','Enable-PnpDevice','Disable-PnpDevice']:
    if re.search(r'(?im)^\s*'+re.escape(token)+r'\b',health): errors.append('health mutation token: '+token)
if errors:
    for e in errors: print('FAIL:',e)
    print(f'setup inventory validation: FAIL ({len(errors)} issue(s))')
    sys.exit(1)
print('setup inventory validation: PASS')
